####################################################################################################
#                                                                                                  #
# (c) 2018 Quantstamp, Inc. All rights reserved.  This content shall not be used, copied,          #
# modified, redistributed, or otherwise disseminated except to the extent expressly authorized by  #
# Quantstamp for credentialed users. This content and its use are governed by the Quantstamp       #
# Demonstration License Terms at <insert link>.                                                    #
#                                                                                                  #
####################################################################################################

version: 0.1
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - echo Pulling the latest image as a cache...
      - docker pull $REPO_URL/$REF_NAME:$REF_TAG || true
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker build --cache-from $REPO_URL/$REF_NAME:$REF_TAG --tag $REPO_URL/$REF_NAME:$REF_TAG --tag $REPO_URL/$REF_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - echo Pushing the Docker image...
      - docker push $REPO_URL/$REF_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $REPO_URL/$REF_NAME:$REF_TAG
      - sed -i -e "s@{{image}}@$REPO_URL/$REF_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION@g" ./deployment/aws-elasticbeanstalk/app/Dockerrun.aws.json
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: deployment/aws-elasticbeanstalk/app
