version: 0.1
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1 --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Pulling the base image...
      - docker pull 466368306539.dkr.ecr.us-east-1.amazonaws.com/qsp-network-audit-base:latest
      - echo Building the Docker image...
      - docker build -t qsp-network-audit .
      - docker tag qsp-network-audit 466368306539.dkr.ecr.us-east-1.amazonaws.com/qsp-network-audit:develop
      - echo Pushing the Docker image...
      - docker push 466368306539.dkr.ecr.us-east-1.amazonaws.com/qsp-network-audit:develop
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '.ebextensions/**/*'
    - Dockerrun.aws.json
cache:
  paths:
    - '/var/lib/docker/**/*'
