version: 0.1
phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install web3[tester]
  build:
    commands:
      - export ENV=local_docker
      - make test
      - coveralls
  post_build:
    commands:
      - echo Build completed on `date`
