####################################################################################################
#                                                                                                  #
# (c) 2018, 2019 Quantstamp, Inc. This content and its use are governed by the license terms at    #
# <https://s3.amazonaws.com/qsp-protocol-license/V2_LICENSE.txt>                                   #
#                                                                                                  #
####################################################################################################

version: 0.1
phases:
  pre_build:
    commands:
      - ls -lhtr $CODEBUILD_SRC_DIR/deployment/
      - cp -R $CODEBUILD_SRC_DIR_DeploymentSourceArtifact/* $CODEBUILD_SRC_DIR/deployment/
      - ls -lhtr $CODEBUILD_SRC_DIR/deployment/
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - echo Pulling the latest image as a cache...
      - docker pull $REPO_URL/$REF_NAME:$REF_TAG || true
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker build --cache-from $REPO_URL/$REF_NAME:$REF_TAG --tag $REPO_URL/$REF_NAME:$REF_TAG --tag $REPO_URL/$REF_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - echo Pushing the Docker image...
      - docker push $REPO_URL/$REF_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $REPO_URL/$REF_NAME:$REF_TAG
      - sed -i -e "s@{{image}}@$REPO_URL/$REF_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION@g" ./deployment/aws-elasticbeanstalk/app/Dockerrun.aws.json
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/deployment/aws-elasticbeanstalk/app
