version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - bash ./scripts/push_image.sh -s
  post_build:
    commands:
      - echo Build completed on `date`
