version: 0.1
phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install web3[tester]
      - wget https://github.com/ethereum/solidity/releases/download/v0.4.21/solc-static-linux
      - chmod +x solc-static-linux
      - mv solc-static-linux /usr/local/bin/solc
  build:
    commands:
      - make test
      - apt-get -y install git # required for coveralls 
      - coveralls
  post_build:
    commands:
      - echo Build completed on `date`
