local:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "http://eth.quantstamp.com:8888/geth/http/ropsten"
  audit_contract_abi:
    uri: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.abi.json"
    metadata: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.meta.json"
  min_price: !!int 0
  evt_polling_sec: !!int 5
  analyzers:
    - oyente:
        args: "-ce"
        storage_dir: /tmp/oyente
        timeout_sec: 120
    - mythril:
        args: "" # No args provided; rely on defaults for now
        storage_dir: /tmp/mythril
        timeout_sec: 120
  report_uploader:
      provider: !!str "S3Provider"
      args:
        bucket_name: "qsp-protocol-reports-dev"
  account:
    id: !!str "0x60463b7ee0c3d33def3a05313597b1300f6de62b"
    keystore_file: !!str "./keystore/UTC--2018-07-10T18-06-47.640663810Z--60463b7ee0c3d33def3a05313597b1300f6de62b"
  default_gas: !!int 500000
  gas_price_wei: !!int 8000000000
  logging:
    is_verbose: True
    streaming:
      provider: !!str "CloudWatchProvider"
      args:
        log_group: "qsp-protocol-nodes-dev"
        log_stream: "node-{id}"
        send_interval_seconds: 30
  metric_collection:
    is_enabled: True
    interval_seconds: 30

dev:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "http://eth.quantstamp.com:8888/geth/http/ropsten"
  audit_contract_abi:
    uri: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.abi.json"
    metadata: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.meta.json"
  min_price: !!int 0
  evt_polling_sec: !!int 5
  analyzers:
    - oyente: 
        args: "-ce"
        storage_dir: /tmp/oyente
        timeout_sec: 300
    - mythril:
        args: "" # No args provided; rely on defaults for now
        storage_dir: /tmp/mythril
        timeout_sec: 300
  report_uploader:
      provider: !!str "S3Provider"
      args:
        bucket_name: "qsp-protocol-reports-dev"
  account:
    id: !!str "0x74a8845b7ef57e7a7d02020e295810cccd3fccfc"
    keystore_file: !!str "/app/keystore/UTC--2018-06-24T19-23-21.176667025Z--74a8845b7ef57e7a7d02020e295810cccd3fccfc"
  default_gas: !!int 700000
  gas_price_wei: !!int 4000000000
  evt_db_path: "/app/audit-db/audit_node.db"
  submission_timeout_limit_blocks: 10
  logging:
    is_verbose: True
    streaming:
      provider: !!str "CloudWatchProvider"
      args:
        log_group: "qsp-protocol-nodes-dev"
        log_stream: "node-{id}"
        send_interval_seconds: 30
  metric_collection:
    is_enabled: True
    interval_seconds: 30

prod:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "http://geth:8545"
  audit_contract_abi:
    uri: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-prod/QuantstampAudit.abi.json"
    metadata: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-prod/QuantstampAudit.meta.json"
  min_price: !!int 0
  evt_polling_sec: !!int 5
  analyzers:
    - oyente:
        args: "-ce"
    - mythril:
        args: "" # No args provided; rely on defaults for now
  report_uploader:
      provider: !!str "S3Provider"
      args:
        bucket_name: "qsp-protocol-reports-prod"
  account:
    ttl: 600
  default_gas: !!int 700000
  gas_price_wei: !!int 4000000000
  evt_db_path: "/app/audit-db/audit_node.db"
  submission_timeout_limit_blocks: 10
  logging:
    is_verbose: True
    streaming:
      provider: !!str "CloudWatchProvider"
      args:
        log_group: "qsp-protocol-nodes-prod"
        log_stream: "node-{id}"
        send_interval_seconds: 30
  metric_collection:
    is_enabled: True
    interval_seconds: 30
