local:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "http://ec2-52-91-149-89.compute-1.amazonaws.com:8545"
  internal_contract_abi:
    uri: !!str "https://s3.amazonaws.com/qsp-network-contract-abi-dev/QuantstampInternal.abi.json"
    metadata: !!str "https://s3.amazonaws.com/qsp-network-contract-abi-dev/QuantstampInternal.meta.json"
  min_price: !!int 0
  evt_polling_sec: !!int 5
  analyzer:
      output: !!str ${input}.json # either a file name or stdout
      cmd: !!str "/oyente/oyente/oyente.py -j -s ${input}"
      solidity: !!str "0.4.17"
  account:
    id: !!str "0xdbc1dc08bd84175c3a1a6daa2bc56f09b7469418"
    ttl: 600

dev:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "http://geth-qsp:8545"
  internal_contract_abi:
    uri: !!str "https://s3.amazonaws.com/qsp-network-contract-abi-dev/QuantstampInternal.abi.json"
    metadata: !!str "https://s3.amazonaws.com/qsp-network-contract-abi-dev/QuantstampInternal.meta.json"
  min_price: !!int 0
  evt_polling_sec: !!int 5
  analyzer:
      output: !!str ${input}.json # either a file name or stdout
      cmd: !!str "/oyente/oyente/oyente.py -j -s ${input}"
      solidity: !!str "0.4.17"
  account:
    id: !!str "0xdbc1dc08bd84175c3a1a6daa2bc56f09b7469418"
    ttl: 259200
