local:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "http://eth.quantstamp.com/geth/ropsten"
  internal_contract_abi:
    uri: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.abi.json"
    metadata: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.meta.json"
  min_price: !!int 0
  evt_polling_sec: !!int 5
  analyzer:
      output: !!str ${input}.json # either a file name or stdout
      cmd: !!str "oyente -j -s ${input}"
  report_uploader:
      provider: !!str "S3Provider"
      args:
        bucket_name: "qsp-protocol-reports-dev"
  account:
    id: !!str "0x0283c049ed4705e2d98c807dbafdaf725f34b8d2"
    ttl: 600

local_docker:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "http://eth.quantstamp.com/geth/ropsten"
  internal_contract_abi:
    uri: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.abi.json"
    metadata: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.meta.json"
  min_price: !!int 0
  evt_polling_sec: !!int 5
  analyzer:
      output: !!str ${input}.json # either a file name or stdout
      cmd: !!str "/oyente/oyente/oyente.py -j -s ${input}"
  report_uploader:
      provider: !!str "S3Provider"
      args:
        bucket_name: "qsp-protocol-reports-dev"
  account:
    id: !!str "0x0283c049ed4705e2d98c807dbafdaf725f34b8d2"
    ttl: 600

dev:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "http://geth:8545"
  internal_contract_abi:
    uri: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.abi.json"
    metadata: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.meta.json"
  min_price: !!int 0
  evt_polling_sec: !!int 5
  analyzer:
      output: !!str ${input}.json # either a file name or stdout
      cmd: !!str "/oyente/oyente/oyente.py -j -s ${input}"
  report_uploader:
      provider: !!str "S3Provider"
      args:
        bucket_name: "qsp-protocol-reports-dev"
  account:
    ttl: 600
  default_gas: !!int 700000
  evt_db_path: "/analyzer/audit-db/audit_node.db"
  submission_timeout_limit_blocks: 10

prod:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "http://geth:8545"
  internal_contract_abi:
    uri: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-prod/QuantstampAudit.abi.json"
    metadata: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-prod/QuantstampAudit.meta.json"
  min_price: !!int 0
  evt_polling_sec: !!int 5
  analyzer:
      output: !!str ${input}.json # either a file name or stdout
      cmd: !!str "/oyente/oyente/oyente.py -j -s ${input}"
  report_uploader:
      provider: !!str "S3Provider"
      args:
        bucket_name: "qsp-protocol-reports-prod"
  account:
    ttl: 600
  default_gas: !!int 700000
  evt_db_path: "/analyzer/audit-db/audit_node.db"
  submission_timeout_limit_blocks: 10
