local:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "http://eth.quantstamp.com:8888/geth/http/ropsten"
  audit_contract_abi:
    uri: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.abi.json"
    metadata: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.meta.json"
  min_price: !!int 0
  evt_polling_sec: !!int 5
  is_mined_polling_sec: !!int 1
  analyzers:
    - oyente:
        args: "-ce"
        storage_dir: /tmp/oyente
        timeout_sec: 120
    - mythril:
        args: "" # No args provided; rely on defaults for now
        storage_dir: /tmp/mythril
        timeout_sec: 120
  report_uploader:
      provider: !!str "S3Provider"
      args:
        bucket_name: "qsp-protocol-reports-dev"
  account:
    id: !!str "0x4e3277806890f7bbb665b13d5baeb75a9f47d2c3"
    ttl: 600
  default_gas: !!int 500000
  gas_price_wei: !!int 8000000000
  logging:
    is_verbose: True
    streaming:
      provider: !!str "CloudWatchProvider"
      args:
        log_group: "qsp-protocol-nodes-dev"
        log_stream: "node-{id}"
        send_interval_seconds: 30
  metric_collection:
    is_enabled: True
    interval_seconds: 30

dev:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "http://eth.quantstamp.com:8888/geth/http/ropsten"
  audit_contract_abi:
    uri: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.abi.json"
    metadata: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-dev/QuantstampAudit.meta.json"
  min_price: !!int 0
  evt_polling_sec: !!int 5
  is_mined_polling_sec: !!int 1
  analyzers:
    - oyente: 
        args: "-ce"
        storage_dir: /tmp/oyente
        timeout_sec: 300
    - mythril:
        args: "" # No args provided; rely on defaults for now
        storage_dir: /tmp/mythril
        timeout_sec: 300
  report_uploader:
      provider: !!str "S3Provider"
      args:
        bucket_name: "qsp-protocol-reports-dev"
  account:
    id: !!str "0x57b23a26d231d98623be7af8d6098be6fb719034"
    ttl: 600
  default_gas: !!int 700000
  gas_price_wei: !!int 4000000000
  evt_db_path: "/app/audit-db/audit_node.db"
  submission_timeout_limit_blocks: 10
  logging:
    is_verbose: True
    streaming:
      provider: !!str "CloudWatchProvider"
      args:
        log_group: "qsp-protocol-nodes-dev"
        log_stream: "node-{id}"
        send_interval_seconds: 30
  metric_collection:
    is_enabled: True
    interval_seconds: 30

prod:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "http://geth:8545"
  audit_contract_abi:
    uri: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-prod/QuantstampAudit.abi.json"
    metadata: !!str "https://s3.amazonaws.com/qsp-protocol-contract-abi-prod/QuantstampAudit.meta.json"
  min_price: !!int 0
  evt_polling_sec: !!int 5
  is_mined_polling_sec: !!int 1
  analyzers:
    - oyente:
        args: "-ce"
    - mythril:
        args: "" # No args provided; rely on defaults for now
  report_uploader:
      provider: !!str "S3Provider"
      args:
        bucket_name: "qsp-protocol-reports-prod"
  account:
    ttl: 600
  default_gas: !!int 700000
  gas_price_wei: !!int 4000000000
  evt_db_path: "/app/audit-db/audit_node.db"
  submission_timeout_limit_blocks: 10
  logging:
    is_verbose: True
    streaming:
      provider: !!str "CloudWatchProvider"
      args:
        log_group: "qsp-protocol-nodes-prod"
        log_stream: "node-{id}"
        send_interval_seconds: 30
  metric_collection:
    is_enabled: True
    interval_seconds: 30
