####################################################################################################
#                                                                                                  #
# (c) 2018 Quantstamp, Inc. All rights reserved.  This content shall not be used, copied,          #
# modified, redistributed, or otherwise disseminated except to the extent expressly authorized by  #
# Quantstamp for credentialed users. This content and its use are governed by the Quantstamp       #
# Demonstration License Terms at <https://s3.amazonaws.com/qsp-protocol-license/LICENSE.txt>.      #
#                                                                                                  #
####################################################################################################

testnet:
  eth_provider:
    name: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "https://ropsten.infura.io/v3/${auth_token}"
  
  qsp_contract:
    uri: !!str "./resources/contracts/dev/QuantstampAudit-v-${major_version}-abi.json"
    metadata: !!str "./resources/contracts/dev/QuantstampAudit-v-${major_version}-meta.json"
  
  min_audit_price_qsp: !!int 10
  max_assigned_requests: !!int 5
  evt_polling_sec: !!int 5
  evt_db_path: !!str "./audit_node.db"
  block_mined_polling_sec: !!int 1
  block_discard_on_restart: !!int 1
  start_n_blocks_in_the_past: !!int 10
  submission_timeout_n_blocks: !!int 10
  transaction_confirmation_n_blocks: !!int 6
  
  analyzers:
    - mythril:
        args: !!str "" # No args provided; rely on defaults for now
        storage_dir: !!str "/tmp/mythril"
        timeout_sec: !!int 276
    - securify:
        args: "" # No args provided; rely on defaults for now
        storage_dir: !!str "/tmp/securify"
        timeout_sec: !!int 276
  
  upload_provider:
      is_enabled: !!bool True
      name: !!str "S3Provider"
      args:
        report_bucket_name: !!str "qsp-protocol-reports-dev"
        contract_bucket_name: !!str "qsp-protocol-reports-dev"

  gas_price_calculator:
    limit: !!int 500000

    # Can be set to either dynamic (compute average gas price of recent blocks) or static (fixed gas price)
    strategy: !!str "dynamic"
    
    # Only used if strategy is set to "static"
    default_price_wei: !!int 8000000000 # 8 Gwei

    # Sets an upper bound on gas_price which would override high values computed by the strategy.
    # Useful in case the network gets "gas attacked".
    # Only used if strategy is set to "dynamic"
    max_price_wei: !!int 50000000000 # 50 Gwei

  log_stream_provider:
    is_enabled: !!bool False
    name: !!str "CloudWatchProvider"
    args:
      group: !!str "qsp-protocol-nodes-dev"
      stream_name: !!str "node-${id}"
      send_interval_seconds: !!int 30

  metrics_collector:
    is_enabled: !!bool True
    interval_seconds: !!int 30
    endpoint_uri: !!str "https://dev-qsp-dashboard.quantstamp.com/node-metrics"
  
  heartbeat_allowed: !!bool False
