log_stream_provider:
  factory:
    module: "streaming.factory.log_stream_factory"
    class: "LogStreamProviderFactory"
  type: "mandatory"
  init_order: 1

private_key:
  factory:
    module: ""eth.factory.pk_factory""
    class: "PrivateKeyFactory"
  type: "internal"
  init_order: 2

eth_provider:
  factory:
    module: "eth.factory.eth_provider_factory"
    class:  "EthProviderFactory"
  type: "mandatory"
  init_order: 3

web3_client:
  factory:
    module: "eth.factory.web3_factory"
    class: "Web3Factory"
  type: internal
  init_order: 4

qsp_contract:
  factory:
    module: "audit.factory.qsp_protocol_factory"
    class: "QSPContractFactort"
  type: mandatory
  init_order: 5

analyzers:
  factory:
    module: # TODO
    class: # TODO
  type: mandatory
  init_order: 6

upload_provider:
  factory:
    module: "upload.factory.upload_provider_factory"
    class: "UploadProviderFactory"
  type: optional
  init_order: 7

gas_price_provider:
  factory:
    module: "eth.factory.eth_provider_factory"
    class: "GasPriceCalculator"
  type: mandatory
  init_order: 8
