log_stream_provider:
  factory:
    module: "streaming.factory.log_stream_factory"
    class: "LogStreamProviderFactory"
  init_order: 1

eth_provider:
  factory:
    module: "eth.factory.eth_provider_factory"
    class:  "EthProviderFactory"
  init_order: 2

qsp_contract:
  factory:
    module: # TODO
    class: # TODO
  init_order: 3

analyzers:
  factory:
    module: # TODO
    class: # TODO
  init_order: 4

upload_provider:
  factory:
    module: "upload.factory.upload_provider_factory"
    class: "UploadProviderFactory"
  init_order: 5

gas_price_provider:
  factory:
    module: # TODO
    class: # TODO
  init_order: 6

