####################################################################################################
#                                                                                                  #
# (c) 2018 Quantstamp, Inc. All rights reserved.  This content shall not be used, copied,          #
# modified, redistributed, or otherwise disseminated except to the extent expressly authorized by  #
# Quantstamp for credentialed users. This content and its use are governed by the Quantstamp       #
# Demonstration License Terms at <https://s3.amazonaws.com/qsp-protocol-license/LICENSE.txt>.                                                    #
#                                                                                                  #
####################################################################################################

testnet:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "https://ropsten.infura.io/v3/${token}"
  audit_contract_abi:
    uri: !!str "./contracts/dev/QuantstampAudit-v-{major-version}-abi.json"
    metadata: !!str "./contracts/dev/QuantstampAudit-v-{major-version}-meta.json"
  audit_data_contract_abi:
    uri: !!str "./contracts/dev/QuantstampAuditData-v-{major-version}-abi.json"
    metadata: !!str "./contracts/dev/QuantstampAuditData-v-{major-version}-meta.json"
  min_price_in_qsp: !!int 10
  max_assigned_requests: !!int 5
  evt_polling_sec: !!int 5
  block_mined_polling_interval_sec: !!int 1
  block_discard_on_restart: !!int 1
  start_n_blocks_in_the_past: !!int 10
  analyzers:
    - mythril:
        args: "" # No args provided; rely on defaults for now
        storage_dir: /tmp/mythril
        timeout_sec: 276
    - securify:
        args: "" # No args provided; rely on defaults for now
        storage_dir: /tmp/securify
        timeout_sec: 276
  report_uploader:
      is_enabled: False
      provider: !!str "S3Provider"
      args:
        bucket_name: "qsp-protocol-reports-dev"
        contract_bucket_name: "qsp-protocol-reports-dev"
  keystore_file: !!str "./keystore/default.json"
  gas_limit: !!int 500000
  gas_price:
    # Can be set to either dynamic (compute average gas price of recent blocks) or static (fixed gas price)
    strategy: !!str "dynamic"
    # Only used if strategy is set to "static"
    default_gas_price_wei: !!int 8000000000 # 8 Gwei
    # Sets an upper bound on gas_price which would override high values computed by the strategy.
    # Useful in case the network gets "gas attacked".
    # Only used if strategy is set to "dynamic"
    max_gas_price_wei: !!int 50000000000 # 50 Gwei
  logging:
    streaming:
      is_enabled: False
      provider: !!str "CloudWatchProvider"
      args:
        log_group: "qsp-protocol-nodes-dev"
        log_stream: "node-{id}"
        send_interval_seconds: 30
  metric_collection:
    is_enabled: True
    interval_seconds: 30
    destination_endpoint: !!str "https://dev-qsp-dashboard.quantstamp.com/node-metrics"
  heartbeat_allowed: False

mainnet:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "https://mainnet.infura.io/v3/${token}"
  audit_contract_abi:
    uri: !!str "./contracts/prod/QuantstampAudit-v-{major-version}-abi.json" #note that v1 production ABI is not available
    metadata: !!str "./contracts/prod/QuantstampAudit-v-{major-version}-meta.json" #note that v1 production ABI is not available
  audit_data_contract_abi:
    uri: !!str "./contracts/prod/QuantstampAuditData-v-{major-version}-abi.json" #note that v1 production ABI is not available
    metadata: !!str "./contracts/prod/QuantstampAuditData-v-{major-version}-meta.json" #note that v1 production ABI is not available
  min_price_in_qsp: !!int 1000
  max_assigned_requests: !!int 5
  evt_polling_sec: !!int 5
  block_mined_polling_interval_sec: !!int 1
  block_discard_on_restart: !!int 1
  analyzers:
    - mythril:
        args: "" # No args provided; rely on defaults for now
        storage_dir: /tmp/mythril
        timeout_sec: 276
    - securify:
        args: "" # No args provided; rely on defaults for now
        storage_dir: /tmp/securify
        timeout_sec: 276
  report_uploader:
      is_enabled: False
  keystore_file: !!str "./keystore/default.json"
  gas_limit: !!int 500000
  gas_price:
    # Can be set to either dynamic (compute average gas price of recent blocks) or static (fixed gas price)
    strategy: !!str "dynamic"
    # Only used if strategy is set to "static"
    default_gas_price_wei: !!int 8000000000 # 8 Gwei
    # Sets an upper bound on gas_price which would override high values computed by the strategy.
    # Useful in case the network gets "gas attacked".
    # Only used if strategy is set to "dynamic"
    max_gas_price_wei: !!int 50000000000 # 50 Gwei
  logging:
    streaming:
      is_enabled: False
      provider: !!str "CloudWatchProvider"
      args:
        log_group: "qsp-protocol-nodes-prod"
        log_stream: "node-{id}"
        send_interval_seconds: 30
  metric_collection:
    is_enabled: True
    interval_seconds: 30
    destination_endpoint: !!str "https://qsp-dashboard.quantstamp.com/node-metrics"
